"""Criando tabela de fas

Revision ID: f8703ec1fef8
Revises: 
Create Date: 2025-04-24 23:34:38.166536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8703ec1fef8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('local', sa.String(), nullable=False),
    sa.Column('jogo_favorito', sa.String(), nullable=False),
    sa.Column('modalidades', sa.JSON(), nullable=False),
    sa.Column('acompanha_esports', sa.Boolean(), nullable=True),
    sa.Column('acompanha_streamers', sa.Boolean(), nullable=True),
    sa.Column('redes_sociais', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fans_id'), 'fans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fans_id'), table_name='fans')
    op.drop_table('fans')
    # ### end Alembic commands ###
